### Case 2

#### 2) A brand new client sent you two ready-to-go queries. Those are listed below:

Query 1:

```
SELECT
      STORE_CODE,
      STORE_NAME,
      START_DATE,
      END_DATE,
      BUSINESS_NAME,
      BUSINESS_CODE
FROM data_store_cad
```
Query 2:

```
SELECT
        STORE_CODE,
        DATE,
        SALES_VALUE,
        SALES_QTY
FROM data_store_sales
WHERE DATE BETWEEN '2019-01-01' AND '2019-12-31'
```
In addition, he gave you this set of instructions:

- Use the queries as they are (do not modify them or create a new one);

- Please filter the period between this given range: 
  - ['2019-10-01','2019-12-31']


<details>
 <summary><b> We are in need of this visualization (click here to see it)! Please, create it with Python</b></summary>
  
| Loja           | Categoria   | TM    | 
|----------------|-------------|-------| 
| Bahia          | Atacado     | 15.39 | 
| Bangkok        | Posto       | 13.67 | 
| Belem          | Proximidade | 15.37 | 
| Berlin         | Proximidade | 15.39 | 
| Buenos Aires   | Atacado     | 15.39 | 
| Chicago        | Varejo      | 15.53 | 
| Dubai          | Atacado     | 15.39 | 
| Hong Kong      | Farma       | 26.35 | 
| London         | Farma       | 28.99 | 
| Madri          | Farma       | 29.03 | 
| Miami          | Posto       | 13.67 | 
| New York       | Proximidade | 15.39 | 
| Paris          | Proximidade | 15.39 | 
| Rio de Janeiro | Farma       | 29.59 | 
| Roma           | Varejo      | 15.39 | 
| Salvador       | Atacado     | 15.39 | 
| Sao Paulo      | Varejo      | 15.39 | 
| Sidney         | Posto       | 13.67 | 
| Tokio          | Varejo      | 15.39 | 
| Vancouver      | Posto       | 13.67 | 
  
</details>

In [2]:
import pandas as pd
from sqlalchemy import create_engine

In [8]:
def retrieve_data():
    # 1. Credenciais de acesso
    usuario = 'looqbox-challenge'
    senha = 'looq-challenge'
    host = '35.199.115.174'
    porta = '3306'          # porta padrão do MySQL
    nome_do_banco = 'looqbox-challenge'

    # 2. String de conexão (URL de conexão)
    # Formato: mysql+pymysql://usuario:senha@host:porta/nome_do_banco
    string_conexao = f'mysql+pymysql://{usuario}:{senha}@{host}:{porta}/{nome_do_banco}'

    # 3. Motor de conexão (engine)
    engine = create_engine(string_conexao)

    # 4. Consulta SQL
    query1 = """SELECT
        STORE_CODE,
        STORE_NAME,
        START_DATE,
        END_DATE,
        BUSINESS_NAME,
        BUSINESS_CODE
        FROM `looqbox-challenge`.`data_store_cad`;
        """
    
    query2 = """SELECT
        STORE_CODE,
        DATE,
        SALES_VALUE,
        SALES_QTY
        FROM `looqbox-challenge`.`data_store_sales`
        WHERE DATE BETWEEN '2019-01-01' AND '2019-12-31'
        """

    df1 = pd.read_sql(query1, con=engine)
    df2 = pd.read_sql(query2, con=engine)

    # 6. retorna o DataFrame
    return df1, df2

In [9]:
df1, df2 = retrieve_data()

In [10]:
df1.head()

   STORE_CODE STORE_NAME  START_DATE END_DATE BUSINESS_NAME  BUSINESS_CODE
0           1  Sao Paulo  2006-10-01                 Varejo              1
1           2    Chicago  2007-10-01                 Varejo              1
2           3       Roma  2008-10-01                 Varejo              1
3           4      Tokio  2009-10-01                 Varejo              1
4           5      Paris  2019-01-01            Proximidade              2

In [11]:
df2.head()

   STORE_CODE        DATE  SALES_VALUE  SALES_QTY
0           1  2019-01-01    196623.22      12838
1          10  2019-01-01    126795.44       4933
2          11  2019-01-01    223937.00       7724
3          12  2019-01-01    200251.80       7043
4          13  2019-01-01    196623.22      12838

In [21]:
df = pd.merge(df2, df1, on='STORE_CODE', how='left')
df = df[['STORE_NAME','BUSINESS_NAME','SALES_VALUE','SALES_QTY']]
df = df.groupby(['STORE_NAME','BUSINESS_NAME']).agg({'SALES_VALUE':'sum','SALES_QTY':'sum'}).reset_index()
df['TM'] = df['SALES_VALUE'] / df['SALES_QTY']
df =df.drop(columns=['SALES_VALUE','SALES_QTY'])
df.rename(columns={'STORE_NAME':'Loja','BUSINESS_NAME':'Categoria'}, inplace=True)
df['TM'] = df['TM'].round(2)
df

              Loja    Categoria     TM
0            Bahia      Atacado  15.39
1          Bangkok        Posto  13.67
2            Belem  Proximidade  15.37
3           Berlin  Proximidade  15.39
4     Buenos Aires      Atacado  15.39
5          Chicago       Varejo  15.53
6            Dubai      Atacado  15.39
7        Hong Kong        Farma  26.33
8           London        Farma  28.96
9            Madri        Farma  29.00
10           Miami        Posto  13.67
11        New York  Proximidade  15.39
12           Paris  Proximidade  15.39
13  Rio de Janeiro        Farma  29.56
14            Roma       Varejo  15.39
15        Salvador      Atacado  15.39
16       Sao Paulo       Varejo  15.39
17          Sidney        Posto  13.67
18           Tokio       Varejo  15.39
19       Vancouver        Posto  13.67